version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # server:
  #   build: ./server
  #   ports:
  #     - '3001:3001'
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/fullstack_db
  #   depends_on:
  #     - db

  # client:
  #   build: ./client
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - server

volumes:
  pgdata:
